# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: aws_single_pavm

# label should be a human readable label that conveys what this skillet will do
label: AWS Single Pan-OS VM-Series with Bootstrap

# description is a longer more informative version of a label
description: AWS Single Pan-OS VM-Series with S3 Bucket for Bootstrapping

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: aws
  collection:
    - Deploy
    - Public Cloud


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: AWS Access Key
    default: access_key
    type_hint: text
  - name: secret_key
    description: AWS Secret Key
    default:
    type_hint: password
  - name: pavm_key_name
    description: SSH Key Name
    default: ssh_key_pair
    type_hint: text
  - name: aws_key_path
    description: Local SSH Key Path
    default: ssh_key_path
    type_hint: text
  - name: region
    description: AWS Region
    default: us-east-2
    type_hint: text
  - name: availability_zone
    description: AWS Availability Zone
    default: us-east-2b
    type_hint: text
  - name: pavm_bootstrap_s3
    description: Bootstrap S3 Bucket Name
    default: s3-something
    type_hint: text


