# edl_with_securityblockrule_panos_v81 adds a basic IP EDL
# also created in and out security blocks rules with EDL as address
# once created the security rule should be moved to the top of the rule list
# associated to John Newsome Minemeld demo

# unique snippet name
name: edl_with_securityblockrule_panos_v81
# label used for menu selection
label: v8.1 EDL with Security Block Rule
description: Add a new IP EDL and associated security block rules
# type of device configuration
type: panos
extends:

# grouping of like snippets for dynamic menu creation in pan-cnc
labels:
  collection:
    - Configure
    - Example Skillets

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: edl_name
    description: Short name for the External Dynamic List (EDL)
    default: block_edl
    type_hint: text
  - name: edl_url
    description: url that the EDL pulls its list from
    default: http://my.edl.url.com/filename.txt
    type_hint: text
  - name: edl_description
    description: brief description for the EDL list context
    default: add the edl description here
    type_hint: text
  - name: logging_profile
    description: Log forwarding profile used in the security rule
    default: default
    type_hint: text


# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: external_list
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list
    file: external_list.xml
  - name: security_rules
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase/security
    file: rulebase_security.xml